name: Continuous integration
on:
  push:
    branches:
      - integration

env:
  PROJECT_ID: ${{ secrets.INT_PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  SA_EMAIL: ${{ secrets.INT_SA_EMAIL }}
  SA_KEY: ${{ secrets.INT_SA_KEY }}

  SERVICE_NAME: patinando-int-edge
  TERRAFORM_VERSION: 0.12.8

jobs:

  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '278.0.0'
          service_account_email: ${{ env.SA_EMAIL }}
          service_account_key: ${{ env.SA_KEY }}
          export_default_credentials: true

      - name: gcloud set project
        run: |
          gcloud config set project $PROJECT_ID

      - name: Build and push
        run: |
          gcloud builds submit -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          cli_config_credentials_token: ${{ secrets.INT_TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: 'deploy'
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: 'deploy'
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: 'deploy'
        id: plan
        run: terraform plan -no-color -out=plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_project: ${{ env.PROJECT_ID }}
          TF_VAR_region: ${{ env.REGION }}
          TF_VAR_run_service_name: ${{ env.SERVICE_NAME }}
          TF_VAR_image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Terraform Apply
        working-directory: 'deploy'
        id: apply
        run: terraform apply plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_VAR_project: ${{ env.PROJECT_ID }}
          TF_VAR_region: ${{ env.REGION }}
          TF_VAR_run_service_name: ${{ env.SERVICE_NAME }}
          TF_VAR_image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
